### ISSUE TITLE
Display number of recent open/closed issues relative to number of monthly downloads

### ISSUE THREAD

**Issue by xiniria** [aantipov/moiva#226]
When comparing two packages that are not quite comparable in terms of number of monthly downloads, the package with the most downloads will usually also be the one with the most issues: the more a package is used, the more people ask questions and report bugs about it. Thus, I think it could be a good idea to propose an option (checkbox?) on the "Recently updated issues" graph to divide, for each compared package, the number of issues/bugs by the number of downloads for the most recent month. That way, a package that is used a lot but still has very few issues will appear very low, which makes it more impressive than a package that has very few open issues because it is not used a lot.

What do you think about this idea?

**Comment by aantipov** [comment]
Hi @xiniria 
Sorry for the late reply (I just realised that I accidentally muted GitHub notifications 🤦 )
I see what you mean.

The suggested approach would work if
- the Number of Issues would be a linear function of the Npm Downloads counts
- the resulted value could be easily comprehended by users (developers) and, as such, bring a value on its own

I highly doubt both.

From my POV the value of the "Recently Updated Issues" is being able to see how actively issues are being worked on - the number of open issues, closed issues, and how these numbers compare to each other (if there is a healthy ratio).

As I'm writing this, I think what would help is to add another dimension to the chart - the ratio of open issues and closed issues. That ratio could be easily compared across the libraries.

WDYT?

**Comment by aantipov** [comment]
I analyzed the data and realised that the chart doesn't really bring much value to Moiva. Often very old closed issues are being updated for different reasons without reopening. Such cases "corrupt" the stats. It's really hard to make any sense out of such data.
Hence, I decided to remove the chart altogether. 
I may add other issues-related stats later.
