### ISSUE TITLE
Support SvelteKit

### ISSUE THREAD

**Issue by benmccann** [aantipov/moiva#518]
I just tried the site and it failed on the first thing I tried:

> Sorry, we couldn't fetch data for @sveltejs/kit

**Comment by aantipov** [comment]
Hi,
thank you for reporting the issue.
The reason for the error is that @sveltejs/kit package doesn't expose repository information.
Hence, Moiva couldn't fetch the required information. There is also no repo information at npmjs.com https://www.npmjs.com/package/@sveltejs/kit

I added the association  between the package and the repository manually in Moiva catalog.
So it works now 
![image](https://user-images.githubusercontent.com/427621/142757329-e995cff0-da8d-4d3b-bd13-9b8d55961d67.png)
